[package]
name = "edabit-challenges"
version = "0.1.0"
edition = "2018"
authors = ["Emil Haugbergsmyr <emil@raeven.net>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"